DROP TABLE MVC_MEMBER;
CREATE TABLE MVC_MEMBER(
    MID VARCHAR2(30),
    MPW VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(30) NOT NULL,
    MEMAIL VARCHAR2(30),
    MPHOTO VARCHAR2(30) DEFAULT 'noimg.jpg' NOT NULL,
    MBIRTH DATE,
    MADDRESS VARCHAR2(300),
    MRDATE DATE DEFAULT SYSDATE,
    PRIMARY KEY(MID)
);

--아이디중복확인--MID로 DTO가져오기
SELECT * FROM MVC_MEMBER WHERE MID='AAA';
--회원가입
INSERT INTO MVC_MEMBER (MID, MPW ,MNAME ,MEMAIL ,MPHOTO ,MBIRTH, MADDRESS)
    VALUES('AAB','111','HONG','JEENPARK@NAVER.COM','noimg.jpg','87/05/24','서울');
--로그인
SELECT * FROM MVC_MEMBER WHERE MID='AAA' AND MPW='111';
--정보수정
UPDATE MVC_MEMBER SET MPW='222', MNAME='KIM', MEMAIL='JEEN@COM', MPHOTO='noimg.jpg', MBIRTH='89/04/04',MADDRESS='대구'
    WHERE MID='AAA';
--목록불러오기
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM MVC_MEMBER ORDER BY MRDATE DESC) A) WHERE RN BETWEEN 1 AND 3;
--전채 명수
SELECT COUNT(*) FROM MVC_MEMBER;
commit;