DROP TABLE BOOK;
DROP TABLE BOOKKIND;
DROP SEQUENCE BOOK_SEQ;
CREATE SEQUENCE BOOK_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
CREATE TABLE BOOK(
    BID NUMBER(7),
    BTITLE VARCHAR2(30) NOT NULL,
    BPRICE NUMBER(7) NOT NULL,
    BIMAGE1 VARCHAR2(30) DEFAULT 'NOTHING.JPG' NOT NULL,
    BIMAGE2 VARCHAR2(30) DEFAULT 'noImg.png' NOT NULL,
    BCONTENT VARCHAR2(4000),
    BDISCOUNT NUMBER(3) NOT NULL,
    BRDATE DATE DEFAULT SYSDATE,
    PRIMARY KEY(BID));
SELECT * FROM BOOK;
COMMIT;
--책 등록
INSERT INTO BOOK(BID ,BTITLE ,BPRICE ,BIMAGE1 ,BIMAGE2 ,BCONTENT ,BDISCOUNT) VALUES(BOOK_SEQ.NEXTVAL, 'java',20000,
'NOTHING.JPG','noImg.png','좋아',10);
INSERT INTO BOOK(BID ,BTITLE ,BPRICE ,BIMAGE1 ,BCONTENT ,BDISCOUNT) VALUES(BOOK_SEQ.NEXTVAL, 'JSP',20000,
'NOTHING.JPG','HIT',10);
INSERT INTO BOOK(BID ,BTITLE ,BPRICE ,BIMAGE2 ,BCONTENT ,BDISCOUNT) VALUES(BOOK_SEQ.NEXTVAL, 'HAH',20000,
'noImg.png','좋아',10);
INSERT INTO BOOK(BID ,BTITLE ,BPRICE,BCONTENT ,BDISCOUNT) VALUES(BOOK_SEQ.NEXTVAL, 'WOW',20000,'좋아',10);
--책 목록
SELECT * FROM BOOK ORDER BY BRDATE DESC;
--책목록(TOP-N) : 페이징
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOOK ORDER BY BRDATE DESC) A) WHERE RN BETWEEN 1 AND 10;
--등록된 책 갯수
SELECT COUNT(*) FROM BOOK;
--BID로 책 가져오기
SELECT * FROM BOOK WHERE BID=3;

UPDATE BOOK SET bimage1='110.jpg', BIMAGE2='101.jpg';