DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    ID VARCHAR2(30),
    PW VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30),
    BIRTH DATE NOT NULL,
    RDATE DATE NOT NULL,
    ADDRESS VARCHAR2(200),
    PRIMARY KEY(ID));
 
ROLLBACK;
COMMIT;   

--1.회원 리스트
SELECT * FROM MEMBER;
--2.회원가입
INSERT INTO MEMBER (ID,PW,NAME,EMAIL,BIRTH,RDATE,ADDRESS) VALUES ('AAA','111','PARK',NULL,'1990-01-01',SYSDATE,'서울시 종로구');
