DROP TABLE FRIEND;
DROP SEQUENCE FRIEND_SEQno;
CREATE SEQUENCE FRIEND_SEQno
    MAXVALUE 9999
    NOCYCLE
    NOCACHE;
CREATE TABLE FRIEND(
    NUM NUMBER(4),
    NAME VARCHAR2(40),
    TEL VARCHAR2(40),
    PRIMARY KEY(NUM));
SELECT * FROM FRIEND;

--친구 추가
INSERT INTO FRIEND VALUES(FRIEND_SEQNO.nextval, 'HONG','010-0000-0000');
COMMIT;