DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    ID VARCHAR2(30),
    PW VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30),
    BIRTH DATE NOT NULL,
    RDATE DATE NOT NULL,
    ADDRESS VARCHAR2(200),
    PRIMARY KEY(ID));
    
SELECT * FROM MEMBER;
--1.회원가입 ID CHK
SELECT COUNT(*) FROM MEMBER WHERE ID='AAA';

--2.회원가입
INSERT INTO MEMBER (ID,PW,NAME,EMAIL,BIRTH,RDATE,ADDRESS) VALUES ('AAA','111','PARK',NULL,'1990-01-01',SYSDATE,'서울시 종로구');
--3.로그인(ID, PW)
SELECT * FROM MEMBER WHERE ID='AAA';    --받아와서 PARAM에서 PW비교
--4.ID로 DTO가져오기
SELECT * FROM MEMBER WHERE ID='AAA';
--5.회원정보 수정
UPDATE MEMBER SET PW='111',
    NAME='HONG', EMAIL='A@A.COM', BIRTH='1990-01-01', ADDRESS='서울시 용산구' WHERE ID='AAA';
    
COMMIT;