DROP TABLE FILEBOARD;
DROP TABLE CUSTOMER;
DROP TABLE BOOK;
CREATE TABLE CUSTOMER(
	CID VARCHAR2(50) PRIMARY KEY,
	CPW VARCHAR2(50) NOT NULL,
	CNAME VARCHAR2(50) NOT NULL,
	CTEL VARCHAR2(50) NOT NULL,
	CEMAIL VARCHAR2(50),
	CADDRESS VARCHAR2(250),
	CBIRTH DATE NOT NULL,
	CGENDER VARCHAR2(10) NOT NULL,
	CRDATE DATE DEFAULT SYSDATE
);
-- 1. 회원가입시 id 중복체크를 위한 SQL
SELECT * FROM CUSTOMER WHERE CID='aaa';
-- 2. 회원가입 SQL
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH) 
    VALUES ('aab','111','홍길동','010-9999-9999', NULL, '서울시 종로구','m','1991-01-01');
-- 3. 로그인할 때 (ID/PW)
SELECT * FROM CUSTOMER WHERE CID='aaa' and CPW='111';
-- 4. ID로 DTO 가져오기
SELECT * FROM CUSTOMER WHERE CID='aaa';
-- 5. 회원정보 수정
UPDATE CUSTOMER SET CPW='111',
                CNAME='엑스맨',
                CTEL = '010-9999-1111',
                CEMAIL='a@a.com',
                CADDRESS='서울시 용산구',
                CBIRTH=to_date('1972-01-12','yyyy-mm-dd'),
                CGENDER = 'm'
        WHERE CID='aaa';
commit;
SELECT * FROM CUSTOMER;