commit;
--★고객 관련★
-- 1. 회원가입시 id 중복체크를 위한 SQL
SELECT * FROM CUSTOMER WHERE CID='aab';
-- 2. 회원가입 SQL
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH) 
    VALUES ('aaa','111','홍길동','010-9999-9999', NULL, '서울시 종로구','m','1991-01-01');
-- 3. 로그인할 때 (ID/PW)
SELECT * FROM CUSTOMER WHERE CID='aaa' and CPW='111';
-- 4. ID로 DTO 가져오기
SELECT * FROM CUSTOMER WHERE CID='aaa';
-- 5. 회원정보 수정
UPDATE CUSTOMER SET CPW='111',
                CNAME='엑스맨',
                CTEL = '010-9999-1111',
                CEMAIL='a@a.com',
                CADDRESS='서울시 용산구',
                CBIRTH=to_date('1972-01-12','yyyy-mm-dd'),
                CGENDER = 'm'
        WHERE CID='aaa';
-- 회원리스트보기(startRow~endRow)
SELECT * FROM (SELECT ROWNUM RN,A.* FROM (SELECT * FROM CUSTOMER ORDER BY CID) A) WHERE RN BETWEEN 1 AND 5;
-- 회원수
SELECT COUNT(*) TOTCNT FROM CUSTOMER;

--★도서관련★
--책 등록
INSERT INTO BOOK(BID ,BTITLE ,BPRICE ,BIMAGE1 ,BIMAGE2 ,BCONTENT ,BDISCOUNT) VALUES(BOOK_SEQ.NEXTVAL, 'java',20000,
'noimg.png','nothing.jpg','좋아',10);
--책 목록
SELECT * FROM BOOK ORDER BY BRDATE DESC;
--책목록(TOP-N) : 페이징
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOOK ORDER BY BRDATE DESC) A) WHERE RN BETWEEN 1 AND 10;
--등록된 책 갯수
SELECT COUNT(*) FROM BOOK;
--BID로 책 가져오기
SELECT * FROM BOOK WHERE BID=3;

--★게시판관련★
--글목록(startRow~endRow)
SELECT * FROM(SELECT ROWNUM RN, A.* FROM(SELECT * FROM FILEBOARD ORDER BY FREF DESC, FRE_STEP) A) WHERE RN BETWEEN 4 AND 6;
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT F.*, CNAME, CEMAIL FROM FILEBOARD F, CUSTOMER C
    WHERE F.CID=C.CID ORDER BY FREF DESC, FRE_STEP) A) WHERE RN BETWEEN 1 AND 2;
--글갯수
SELECT COUNT(*) FROM FILEBOARD;
--글 삽입
INSERT INTO FILEBOARD (FNUM, CID, FSUBJECT, FCONTENT, FFILENAME, FPW, FREF, FRE_STEP, FRE_LEVEL, FIP)
    VALUES(FILEBOARD_SEQ.NEXTVAL, 'aaa', 'title', 'content', 'fileup.jpg', '111',FILEBOARD_SEQ.CURRVAL, 0, 0 , '192.168.29.44');
--답변쓰기 STEP a수행(REF가 같고 원글의 RE_STEP보다 많은경우 RE_STEP++)
UPDATE FILEBOARD SET FRE_STEP = FRE_STEP+1 WHERE FREF=6 AND FRE_STEP>0;
SELECT * FROM FILEBOARD WHERE FREF=6;
INSERT INTO FILEBOARD (FNUM, CID, FSUBJECT, FCONTENT, FFILENAME, FPW, FREF, FRE_STEP, FRE_LEVEL, FIP)
    VALUES(FILEBOARD_SEQ.NEXTVAL, 'aad', 're6-1', 'content', null, '111',6, 1, 1 , '192.168.29.44');
--조회수 올리기
UPDATE FILEBOARD SET FHIT=FHIT+1 WHERE FNUM=3;
--글 상세보기
SELECT F.*, CNAME, CEMAIL FROM FILEBOARD F, CUSTOMER C WHERE F.CID=C.CID AND FNUM=3;
--글 수정하기
UPDATE FILEBOARD SET FSUBJECT='바뀐제목',FCONTENT='바뀐내용',FFILENAME='첨부', FPW='111', FIP='127.0.0.1' WHERE FNUM=3;
--글 삭제하기
    DELETE FROM FILEBOARD WHERE FNUM=7 AND FPW='111';