COMMIT;
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH) 
    VALUES ('aaa','111','홍길동','010-9999-9999', NULL, '서울시 종로구','m','1991-01-01');
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH) 
    VALUES ('aab','111','홍길동','010-9999-9999', NULL, '서울시 종로구','m','1991-01-01');
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH) 
    VALUES ('aac','111','홍길동','010-9999-9999', NULL, '서울시 종로구','m','1991-01-01');
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH) 
    VALUES ('aad','111','홍길동','010-9999-9999', NULL, '서울시 종로구','m','1991-01-01');
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH) 
    VALUES ('aae','111','홍길동','010-9999-9999', NULL, '서울시 종로구','m','1991-01-01');
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH) 
    VALUES ('aaf','111','홍길동','010-9999-9999', NULL, '서울시 종로구','m','1991-01-01');
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH) 
    VALUES ('aag','111','홍길동','010-9999-9999', NULL, '서울시 종로구','m','1991-01-01');
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH) 
    VALUES ('aah','111','홍길동','010-9999-9999', NULL, '서울시 종로구','m','1991-01-01');
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH) 
    VALUES ('aai','111','홍길동','010-9999-9999', NULL, '서울시 종로구','m','1991-01-01');
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH) 
    VALUES ('aaj','111','홍길동','010-9999-9999', NULL, '서울시 종로구','m','1991-01-01');
    
INSERT INTO BOOK(BID ,BTITLE ,BPRICE ,BIMAGE1 ,BIMAGE2 ,BCONTENT ,BDISCOUNT) VALUES(BOOK_SEQ.NEXTVAL, 'java',20000,
'110.jpg','noimg.png','좋아',10);
INSERT INTO BOOK(BID ,BTITLE ,BPRICE ,BIMAGE1 ,BIMAGE2 ,BCONTENT ,BDISCOUNT) VALUES(BOOK_SEQ.NEXTVAL, 'java',20000,
'110.jpg','noimg.png','좋아',10);
INSERT INTO BOOK(BID ,BTITLE ,BPRICE ,BIMAGE1 ,BIMAGE2 ,BCONTENT ,BDISCOUNT) VALUES(BOOK_SEQ.NEXTVAL, 'java',20000,
'110.jpg','noimg.png','좋아',10);
INSERT INTO BOOK(BID ,BTITLE ,BPRICE ,BIMAGE1 ,BIMAGE2 ,BCONTENT ,BDISCOUNT) VALUES(BOOK_SEQ.NEXTVAL, 'java',20000,
'110.jpg','noimg.png','좋아',10);
INSERT INTO BOOK(BID ,BTITLE ,BPRICE ,BIMAGE1 ,BIMAGE2 ,BCONTENT ,BDISCOUNT) VALUES(BOOK_SEQ.NEXTVAL, 'java',20000,
'110.jpg','noimg.png','좋아',10);
INSERT INTO BOOK(BID ,BTITLE ,BPRICE ,BIMAGE1 ,BIMAGE2 ,BCONTENT ,BDISCOUNT) VALUES(BOOK_SEQ.NEXTVAL, 'java',20000,
'110.jpg','noimg.png','좋아',10);
INSERT INTO BOOK(BID ,BTITLE ,BPRICE ,BIMAGE1 ,BIMAGE2 ,BCONTENT ,BDISCOUNT) VALUES(BOOK_SEQ.NEXTVAL, 'java',20000,
'110.jpg','noimg.png','좋아',10);
INSERT INTO BOOK(BID ,BTITLE ,BPRICE ,BIMAGE1 ,BIMAGE2 ,BCONTENT ,BDISCOUNT) VALUES(BOOK_SEQ.NEXTVAL, 'java',20000,
'110.jpg','noimg.png','좋아',10);
INSERT INTO BOOK(BID ,BTITLE ,BPRICE ,BIMAGE1 ,BIMAGE2 ,BCONTENT ,BDISCOUNT) VALUES(BOOK_SEQ.NEXTVAL, 'java',20000,
'110.jpg','noimg.png','좋아',10);
INSERT INTO BOOK(BID ,BTITLE ,BPRICE ,BIMAGE1 ,BIMAGE2 ,BCONTENT ,BDISCOUNT) VALUES(BOOK_SEQ.NEXTVAL, 'java',20000,
'110.jpg','noimg.png','좋아',10);

INSERT INTO FILEBOARD (FNUM, CID, FSUBJECT, FCONTENT, FFILENAME, FPW, FREF, FRE_STEP, FRE_LEVEL, FIP)
    VALUES(FILEBOARD_SEQ.NEXTVAL, 'aaa', 'title', 'content', 'name', '111',FILEBOARD_SEQ.CURRVAL, 0, 0 , '192.168.29.44');
INSERT INTO FILEBOARD (FNUM, CID, FSUBJECT, FCONTENT, FFILENAME, FPW, FREF, FRE_STEP, FRE_LEVEL, FIP)
    VALUES(FILEBOARD_SEQ.NEXTVAL, 'aab', 'title', 'content', 'name', '111',2, 1, 1 , '192.168.29.44');
INSERT INTO FILEBOARD (FNUM, CID, FSUBJECT, FCONTENT, FFILENAME, FPW, FREF, FRE_STEP, FRE_LEVEL, FIP)
    VALUES(FILEBOARD_SEQ.NEXTVAL, 'aac', 'title', 'content', 'name', '111',2, 2, 2 , '192.168.29.44');
INSERT INTO FILEBOARD (FNUM, CID, FSUBJECT, FCONTENT, FFILENAME, FPW, FREF, FRE_STEP, FRE_LEVEL, FIP)
    VALUES(FILEBOARD_SEQ.NEXTVAL, 'aad', 'title', 'content', 'name', '111',2, 3, 3 , '192.168.29.44');
    INSERT INTO FILEBOARD (FNUM, CID, FSUBJECT, FCONTENT, FFILENAME, FPW, FREF, FRE_STEP, FRE_LEVEL, FIP)
    VALUES(FILEBOARD_SEQ.NEXTVAL, 'aaa', 'title', 'content', 'name', '111',FILEBOARD_SEQ.CURRVAL, 0, 0 , '192.168.29.44');
INSERT INTO FILEBOARD (FNUM, CID, FSUBJECT, FCONTENT, FFILENAME, FPW, FREF, FRE_STEP, FRE_LEVEL, FIP)
    VALUES(FILEBOARD_SEQ.NEXTVAL, 'aab', 'title', 'content', 'name', '111',2, 1, 1 , '192.168.29.44');
INSERT INTO FILEBOARD (FNUM, CID, FSUBJECT, FCONTENT, FFILENAME, FPW, FREF, FRE_STEP, FRE_LEVEL, FIP)
    VALUES(FILEBOARD_SEQ.NEXTVAL, 'aac', 'title', 'content', 'name', '111',2, 2, 2 , '192.168.29.44');
INSERT INTO FILEBOARD (FNUM, CID, FSUBJECT, FCONTENT, FFILENAME, FPW, FREF, FRE_STEP, FRE_LEVEL, FIP)
    VALUES(FILEBOARD_SEQ.NEXTVAL, 'aad', 'title', 'content', 'name', '111',2, 3, 3 , '192.168.29.44');


UPDATE FILEBOARD SET FHIT=FHIT+100 WHERE FNUM=90;
UPDATE FILEBOARD SET FFILENAME='fileup.jpg' WHERE FNUM=98;
commit;