DROP TABLE BOARDPR;
CREATE TABLE BOARDPR(
    NUM      NUMBER(5),
    REF      NUMBER(5) NOT NULL,
    RE_STEP  NUMBER(5) DEFAULT 0,
    RE_LEVEL NUMBER(5) DEFAULT 0,
    WRITER   VARCHAR2(30) NOT NULL,
    PW       VARCHAR2(30) NOT NULL,
    CONTENT  VARCHAR2(1000),
    HIT      NUMBER(5) DEFAULT 0,
    IP       VARCHAR2(20) NOT NULL,
    PRIMARY KEY(NUM));

SELECT * FROM BOARDPR;
COMMIT;
--글 목록
SELECT * FROM BOARDPR ORDER BY REF DESC, RE_STEP;
--글 쓰기
INSERT INTO BOARDPR (NUM, REF, WRITER, PW, CONTENT, IP)
    VALUES((SELECT NVL(MAX(NUM),0)+1 FROM BOARDPR),(SELECT NVL(MAX(NUM),0)+1 FROM BOARDPR),
            'PARK', '111', 'BLABLAP', '192.168.20.41');
--덧글 쓰기
INSERT INTO BOARDPR (NUM, REF,re_step, re_level, WRITER, PW, CONTENT,IP)
    VALUES((SELECT NVL(MAX(NUM),0)+1 FROM BOARDPR),3 , 1, 1,
            'REMAN', '111', 'IT IS RECOMENT', '1.1');
--글 갯수
SELECT COUNT(*) CNT FROM BOARDPR;
--글번호로 DTO 호출
SELECT * FROM BOARDPR WHERE NUM=2;
--글 수정
UPDATE BOARDPR SET WRITER = 'LEE', PW = '111', CONTENT = 'FIXIT', IP='0' WHERE NUM=2;
--글 삭제
DELETE FROM BOARDPR WHERE NUM=6 AND PW='111';